### Promise
- 更优的异步编程统一方案， 解决回调地狱
- Promise是一个构造函数， 用来表述一个异步任务执行之后是成功还是失败

```javascript
                     |----------> Fulfilled ---------> onFulfilled()
          pending    | 
Promise -----------> |
                     |
                     |----------> Rejected ---------> onRejected()
```


#### 1.基本用法
```javascript
// promise用法
const promise = new Promise(function(resolve, reject) {
  // resolve(100)
  reject(new Error('promise rejected'))
})

promise.then((value) => {
  console.log('value===>', value);
}, err => {
  console.log('err===>', err);
})

console.log('end');
```


#### 2.链式调用
- 常见误区： 嵌套使用promise; 使用链式调用的方式去保证异步任务的扁平化，否则仍然是一个回调地狱
```javascript
  const promise1 = ajax('/api/users.json')
  // 链式调用
  promise1.then(res => {
    console.log(111);
    // 在then中可以手动返回一个promise对象
    return ajax('/api/urls.json')
  }).then(res => {
    console.log(222, res);
  }).then(res => {
    console.log(333);
    return '232'
  }).then(res => {
    console.log(444);
  })
```
- 理解：
  - then方法会返回一个新的promise对象，所以可以使用链式回调
  - 后面的then方法就是在为上一个then返回的promise注册回调，  前边的then方法回调函数的返回值会作为后边then方法回调的参数
  - 如果在回调中返回Promise，那后面then方法的回调会等待它的结束 
  - 如果回调中没有返回promise而是返回一个值，那么这个值会作为resolve的参数传递，没有的话默认是undefined


#### 3.异常处理
- onRejected: 只能捕获第一个promise的报错，如果当前then的resolve函数处理中有报错是捕获不到的
- .catch(): 是对上一个.then()返回的promise做处理，不过第一个promise的报错也会顺延到catch中

#### 4.promise的一些方法
- Promise.resolve()
- Promise.reject()
- Promise.all()
- Promise.race()







